// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtf8HVOAARQaiK_0pH25f6m7_OODqceOc',
    appId: '1:151303490742:web:37ce2ade76598fb4e36a17',
    messagingSenderId: '151303490742',
    projectId: 'fixnbuy',
    authDomain: 'fixnbuy.firebaseapp.com',
    storageBucket: 'fixnbuy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjhxm3ZPmyyNzl_IiEHouP_Wn1fy2DQxQ',
    appId: '1:151303490742:android:0e4a07bc28960edde36a17',
    messagingSenderId: '151303490742',
    projectId: 'fixnbuy',
    storageBucket: 'fixnbuy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYR2jW5WOJRkm6GR_hfMc-8qbI6KbrhXU',
    appId: '1:151303490742:ios:bbdc49836e39bfa9e36a17',
    messagingSenderId: '151303490742',
    projectId: 'fixnbuy',
    storageBucket: 'fixnbuy.firebasestorage.app',
    iosBundleId: 'com.smoqdev.fixnbuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYR2jW5WOJRkm6GR_hfMc-8qbI6KbrhXU',
    appId: '1:151303490742:ios:bbdc49836e39bfa9e36a17',
    messagingSenderId: '151303490742',
    projectId: 'fixnbuy',
    storageBucket: 'fixnbuy.firebasestorage.app',
    iosBundleId: 'com.smoqdev.fixnbuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtf8HVOAARQaiK_0pH25f6m7_OODqceOc',
    appId: '1:151303490742:web:54f5f1c3967ca4bce36a17',
    messagingSenderId: '151303490742',
    projectId: 'fixnbuy',
    authDomain: 'fixnbuy.firebaseapp.com',
    storageBucket: 'fixnbuy.firebasestorage.app',
  );

}