// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnnhr0fajpNKNWPoen8jaY78QtOQO5vao',
    appId: '1:1029516780358:web:2048853a5f47a040917b47',
    messagingSenderId: '1029516780358',
    projectId: 'myplug-ca',
    authDomain: 'myplug-ca.firebaseapp.com',
    storageBucket: 'myplug-ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZmIyiwppQ0qeAxu-UdRYlK2RTD43o20',
    appId: '1:1029516780358:android:3a37a394c7938e45917b47',
    messagingSenderId: '1029516780358',
    projectId: 'myplug-ca',
    storageBucket: 'myplug-ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEC1UeEepZPYrdTFoZU0zpVZspD7XsU50',
    appId: '1:1029516780358:ios:c29cf08e66413ad3917b47',
    messagingSenderId: '1029516780358',
    projectId: 'myplug-ca',
    storageBucket: 'myplug-ca.firebasestorage.app',
    iosBundleId: 'com.smoq.myplugCa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEC1UeEepZPYrdTFoZU0zpVZspD7XsU50',
    appId: '1:1029516780358:ios:c29cf08e66413ad3917b47',
    messagingSenderId: '1029516780358',
    projectId: 'myplug-ca',
    storageBucket: 'myplug-ca.firebasestorage.app',
    iosBundleId: 'com.smoq.myplugCa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnnhr0fajpNKNWPoen8jaY78QtOQO5vao',
    appId: '1:1029516780358:web:4c1274a3a1ff0ced917b47',
    messagingSenderId: '1029516780358',
    projectId: 'myplug-ca',
    authDomain: 'myplug-ca.firebaseapp.com',
    storageBucket: 'myplug-ca.firebasestorage.app',
  );
}
