import 'package:myplug_ca/features/job/domain/models/job.dart';
import 'package:myplug_ca/features/job/domain/models/job_type.dart';

final List<Job> demoJobs = [
  Job(
    id: 'job1',
    title: 'Flutter Developer',
    description:
        'Build and maintain cross-platform mobile applications using Flutter.',
    salary: 150000.0,
    company: 'Smoq Dev',
    type: JobType.parttime,
    companyLogo: 'https://example.com/logos/smoqdev.png',
    location: 'Lagos',
    date: DateTime.now().subtract(const Duration(days: 1)),
    requirements: [
      '2+ years of Flutter experience',
      'Understanding of BLoC and Provider',
      'Firebase integration skills',
    ],
  ),
  Job(
    id: 'job2',
    title: 'UI/UX Designer',
    type: JobType.internship,
    description:
        'Design beautiful and intuitive user interfaces for mobile and web.',
    salary: 120000.0,
    company: 'Designly',
    companyLogo: 'https://example.com/logos/designly.png',
    location: 'Lagos',
    date: DateTime.now().subtract(const Duration(days: 2)),
    requirements: [
      'Proficiency in Figma or Adobe XD',
      'Strong portfolio of design work',
      'Understanding of mobile design patterns',
    ],
  ),
  Job(
    id: 'job3',
    title: 'Backend Engineer',
    type: JobType.fulltime,
    description:
        'Develop scalable APIs and microservices using Node.js and MongoDB.',
    salary: 180000.0,
    company: 'TechNova',
    companyLogo: 'https://example.com/logos/technova.png',
    location: 'Abuja',
    date: DateTime.now().subtract(const Duration(days: 3)),
    requirements: [
      'Strong knowledge of Node.js',
      'Experience with MongoDB',
      'API design and documentation',
    ],
  ),
  Job(
    id: 'job4',
    title: 'Data Analyst',
    description: 'Analyze datasets to extract meaningful insights and trends.',
    salary: 110000.0,
    type: JobType.internship,
    company: 'DataScope',
    companyLogo: 'https://example.com/logos/datascope.png',
    location: 'Enugu',
    date: DateTime.now().subtract(const Duration(days: 4)),
    requirements: [
      'SQL and Excel expertise',
      'Proficiency in Python or R',
      'Data visualization experience',
    ],
  ),
  Job(
    id: 'job5',
    title: 'Product Manager',
    description: 'Lead product development from ideation to launch.',
    type: JobType.fulltime,
    salary: 200000.0,
    company: 'InnovateX',
    companyLogo: 'https://example.com/logos/innovatex.png',
    location: 'Rivers',
    date: DateTime.now().subtract(const Duration(days: 5)),
    requirements: [
      '3+ years in product management',
      'Agile/Scrum experience',
      'Great communication skills',
    ],
  ),
  Job(
    id: 'job6',
    title: 'DevOps Engineer',
    description: 'Manage CI/CD pipelines and ensure deployment reliability.',
    type: JobType.fulltime,
    salary: 175000.0,
    company: 'CloudGear',
    companyLogo: 'https://example.com/logos/cloudgear.png',
    location: 'Niger',
    date: DateTime.now().subtract(const Duration(days: 6)),
    requirements: [
      'CI/CD tools experience (GitHub Actions, Jenkins)',
      'AWS or GCP knowledge',
      'Docker and Kubernetes proficiency',
    ],
  ),
  Job(
    id: 'job7',
    title: 'QA Tester',
    description: 'Write test cases, identify bugs, and ensure product quality.',
    type: JobType.parttime,
    salary: 95000.0,
    company: 'QualityHub',
    companyLogo: 'https://example.com/logos/qualityhub.png',
    location: 'Lagos',
    date: DateTime.now().subtract(const Duration(days: 7)),
    requirements: [
      'Manual and automated testing experience',
      'Knowledge of Selenium or Appium',
      'Attention to detail',
    ],
  ),
  Job(
    id: 'job8',
    title: 'AI Research Intern',
    description: 'Assist in developing and training machine learning models.',
    type: JobType.internship,
    salary: 85000.0,
    company: 'DeepThink',
    companyLogo: 'https://example.com/logos/deepthink.png',
    location: 'Ebonyi',
    date: DateTime.now().subtract(const Duration(days: 8)),
    requirements: [
      'Understanding of ML concepts',
      'Experience with TensorFlow or PyTorch',
      'Python proficiency',
    ],
  ),
  Job(
    id: 'job9',
    title: 'Technical Writer',
    description: 'Create technical documentation and developer guides.',
    type: JobType.fulltime,
    salary: 100000.0,
    company: 'DocuFlow',
    companyLogo: 'https://example.com/logos/docuflow.png',
    location: 'Ibadan',
    date: DateTime.now().subtract(const Duration(days: 9)),
    requirements: [
      'Excellent writing skills',
      'Familiarity with Markdown',
      'API doc'
    ],
  ),
];
