import 'package:myplug_ca/core/constants/images.dart';
import 'package:myplug_ca/features/product/domain/models/product.dart';
import 'package:myplug_ca/core/domain/models/rating.dart';
import 'package:myplug_ca/core/constants/users.dart';
import 'package:myplug_ca/core/constants/shops.dart';

//products
final List<Product> demoProducts = [
  Product(
    description: 'random desc',
    images: demoImages,
    ratings: [
      Rating(
        comment: 'no review',
        rating: 5,
        username: 'smoq',
        date: DateTime.now(),
      ),
      Rating(
        comment: 'no review',
        rating: 5,
        username: 'smoq',
        date: DateTime.now(),
      ),
      Rating(
        comment: 'no review',
        rating: 3,
        username: 'smoq',
        date: DateTime.now(),
      ),
    ],
    seller: demoUsers[0],
    title: 'title',
    location: 'abuja',
    price: 4900.00,
    shop: shops[0],
  ),
  Product(
      description: 'random desc',
      images: [],
      ratings: [],
      seller: demoUsers[0],
      title: 'title',
      location: 'abuja',
      price: 4900.00,
      shop: shops[2]),
  Product(
    description: 'random desc',
    images: [],
    ratings: [
      Rating(
          comment: 'Nice product',
          rating: 5,
          username: 'smoq',
          date: DateTime.now()),
      Rating(
          comment: 'Works well',
          rating: 4,
          username: 'smoq',
          date: DateTime.now()),
    ],
    seller: demoUsers[0],
    title: 'Smart Watch X',
    location: 'Abuja',
    price: 4900.00,
    shop: shops[0],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [
      Rating(
          comment: 'Not bad',
          rating: 4,
          username: 'smoq',
          date: DateTime.now()),
    ],
    seller: demoUsers[1],
    title: 'Bluetooth Speaker Pro',
    location: 'Lagos',
    price: 5500.00,
    shop: shops[1],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [
      Rating(
          comment: 'Amazing quality',
          rating: 5,
          username: 'smoq',
          date: DateTime.now()),
    ],
    seller: demoUsers[0],
    title: 'Portable Charger',
    location: 'Ibadan',
    price: 4300.00,
    shop: shops[0],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [
      Rating(
          comment: 'Works as expected',
          rating: 4,
          username: 'smoq',
          date: DateTime.now()),
    ],
    seller: demoUsers[2],
    title: 'USB-C Cable Pack',
    location: 'Port Harcourt',
    price: 2100.00,
    shop: shops[2],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [
      Rating(
          comment: 'Stylish design',
          rating: 5,
          username: 'smoq',
          date: DateTime.now()),
    ],
    seller: demoUsers[1],
    title: 'Wireless Earbuds',
    location: 'Enugu',
    price: 7900.00,
    shop: shops[1],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [
      Rating(
          comment: 'Could be better',
          rating: 3,
          username: 'smoq',
          date: DateTime.now()),
    ],
    seller: demoUsers[0],
    title: 'Fitness Tracker',
    location: 'Kaduna',
    price: 4600.00,
    shop: shops[0],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[2],
    title: 'Mini Tripod Stand',
    location: 'Benin',
    price: 3100.00,
    shop: shops[2],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[0],
    title: 'LED Ring Light',
    location: 'Jos',
    price: 6800.00,
    shop: shops[0],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[1],
    title: 'Laptop Cooling Pad',
    location: 'Abeokuta',
    price: 5700.00,
    shop: shops[1],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[2],
    title: 'Wireless Mouse',
    location: 'Ilorin',
    price: 3900.00,
    shop: shops[2],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[0],
    title: 'Mechanical Keyboard',
    location: 'Owerri',
    price: 9800.00,
    shop: shops[0],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[1],
    title: 'Phone Holder',
    location: 'Akure',
    price: 2500.00,
    shop: shops[1],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[2],
    title: 'Smartphone Gimbal',
    location: 'Uyo',
    price: 10500.00,
    shop: shops[2],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[0],
    title: 'Action Camera',
    location: 'Kano',
    price: 13900.00,
    shop: shops[0],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[1],
    title: 'Gamepad Controller',
    location: 'Makurdi',
    price: 6100.00,
    shop: shops[1],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[2],
    title: 'HD Webcam',
    location: 'Yola',
    price: 7500.00,
    shop: shops[2],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[0],
    title: 'Stylus Pen',
    location: 'Minna',
    price: 3200.00,
    shop: shops[0],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[1],
    title: 'VR Headset',
    location: 'Lokoja',
    price: 18900.00,
    shop: shops[1],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[2],
    title: 'Noise Cancelling Mic',
    location: 'Calabar',
    price: 8800.00,
    shop: shops[2],
  ),
  Product(
    description: 'random desc',
    images: [],
    ratings: [],
    seller: demoUsers[0],
    title: 'Smart LED Bulb',
    location: 'Sokoto',
    price: 4300.00,
    shop: shops[0],
  ),
];
