import 'package:myplug_ca/features/product/domain/models/myplug_shop.dart';

//shop categories

final List<MyplugShop> shops = [
  MyplugShop(
    id: 1,
    image: "assets/images/shops/house.png",
    name: "Land & Property",
    subshop: [
      "Houses",
      "Land",
      "Event Centers/Workstations/Meeting & conference room",
    ],
  ),
  MyplugShop(
    id: 2,
    image: "assets/images/shops/vehicles.png",
    name: "Vehicles",
    subshop: [
      "Spare parts & Accessories",
      "Cars",
      "Buses & Mini Buses",
      "Trucks & Trailers",
      "Bikes",
    ],
  ),
  MyplugShop(
    id: 3,
    image: "assets/images/shops/smartphones.png",
    name: "Phones / Tablets & Accessories",
    subshop: ["Mobile Phones", "Accessories", "Tablets", "Other Gadgets"],
  ),
  MyplugShop(
    id: 4,
    image: "assets/images/shops/house.png",
    name: "Electronics & Computers",
    subshop: [
      "TV & Monitor",
      "Computers & Laptops",
      "Audio & Music Equipment",
      "Security & Surveillance",
      "Electronic Accessories",
      "Printers & Scanners",
      "Video Game Consoles",
      "Photo and Video Cameras",
      "Softwares",
      "Video Games",
      "Headphones & Other Electronic Gadgets",
    ],
  ),
  MyplugShop(
    id: 5,
    image: "assets/images/shops/furniture.png",
    name: "Home Equipment & Furniture",
    subshop: ["Furniture", "Home Accessories", "Home/Kitchen Appliances"],
  ),
  MyplugShop(
    id: 6,
    image: "assets/images/shops/house.png",
    name: "Fashion",
    subshop: [
      "Clothing",
      "Shoes",
      "Bags",
      "Watches & Other Accessories",
      "Bridal & Accessories",
    ],
  ),
  MyplugShop(
    id: 7,
    image: "assets/images/shops/house.png",
    name: "Beauty Treatments",
    subshop: [
      "Soap & Body wash",
      "Skin Care",
      "Tools & Accessories",
      "Fragrances",
      "Make-up",
      "Sexual Enhancement Accessories",
    ],
  ),
  MyplugShop(
    id: 8,
    image: "assets/images/shops/pets.png",
    name: "Animals & Pets",
    subshop: [
      "Dogs & Puppies",
      "Cats & Kitten",
      "Fish",
      "Other Animals",
      "Feeds",
    ],
  ),
  MyplugShop(
    id: 9,
    image: "assets/images/shops/beverages.png",
    name: "Beverages",
    subshop: [
      "Palm wine",
      "Beer",
      "Soft drinks",
      "Juice",
      "Yoghurt",
      "Wine",
      "Gin",
    ],
  ),
  MyplugShop(
    id: 10,
    image: "assets/images/shops/fruits.png",
    name: "Fruits",
    subshop: [
      "Apples",
      "Mangoes",
      "Bananas",
      "Oranges",
      "Paw Paw",
      "Water Melon",
      "Cucumber",
      "Cherries",
    ],
  ),
  MyplugShop(
    id: 11,
    image: "assets/images/shops/icecream.png",
    name: "Pastries",
    subshop: ["Ice Cream", "Parfait", "Shawarma", "Burgers", "Smoothie"],
  ),
  MyplugShop(
    id: 12,
    image: "assets/images/shops/house.png",
    name: "Food Stuffs",
    subshop: [
      "Garri",
      "Rice",
      "Beans",
      "Corn",
      "Yam",
      "Plantain",
      "Beef",
      "Chicken",
      "Pork",
      "Fish",
      "Stockfish",
      "Crayfish",
    ],
  ),
];
